[general]
name = "mpfr-fix"
version = "0.3.0"
fix_version = "1.3.0"
description = "MPFR bindings for the Fix programming language."

[build]
files = ["mpfr.fix"]
dynamic_links = ["mpfr", "gmp"]

[build.test]
files = ["mpfr-test.fix"]
memcheck = true


[[dependencies]]
name = "gmp-fix"
version = "0.7.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-gmp.git" }
